---

  - name: Create the node_exporter group
    group:
      name: node_exporter
      state: present
      system: true
    tags: ["kiosk", "extras", "node"]         

  - name: create node_export user
    action: user name=node_exporter group=node_exporter state=present
    tags: ["kiosk", "extras", "node"]  
          
  - name: Copy the node_exporter systemd service file
    template:
      src: roles/node/service/node_exporter.service
      dest: /etc/systemd/system/node_exporter.service
      owner: node_exporter
      group: node_exporter
      mode: 0644
    tags: ["kiosk", "extras", "node"]    
          
  - name: Copy Node Exporter
    copy: 
      src: roles/node/node_exporter-1.3.1/node_exporter
      dest: /usr/local/bin/node_exporter
      mode: 0777
    tags: ["kiosk", "extras", "node"] 
      
  - name: Enable Node Exporter
    service:
      name: node_exporter.service
      state: started
      enabled: yes
    tags: ["kiosk", "extras", "node"]     
