---

  - name: Ensure config directory exists
    file:
      path: '{{ kiosk_user_home }}/.ssh'
      state: directory
    tags: ["proxmox", "ssh"]      
                  
  - name: Copy over Kiosk Pub key to Kiosk Home User
    copy:
      dest: '{{ kiosk_user_home }}/.ssh/authorized_keys'
      mode: 0600
      content: |        
         key1    
    tags: ["kiosk", "ssh"]                      

