  - name: Install snmpd
    apt:
      pkg:
      - snmp
      - snmpd
    tags: ["kiosk", "snmp", "extras"]       

  - name: Copy SNMP Conf
    copy:
      dest: /etc/snmp/snmpd.conf
      mode: 0777
      content: |
         sysLocation    Awesome Place
         sysContact     https://github.com/brcak-zmaj
         sysServices    72
         master  agentx
         agentaddress  127.0.0.1,[::1]
         agentAddress udp:127.0.0.1:161
         agentAddress udp:161,udp6:[::1]:161
         view   systemonly  included   .1.3.6.1.2.1.1
         view   systemonly  included   .1.3.6.1.2.1.25.1
         rocommunity  public default -V systemonly
         rocommunity6 public default -V systemonly
         rouser authPrivUser authpriv -V systemonly          
    tags: ["kiosk", "snmp", "extras"]    

    
    
    
    
    

