  - name: Install Cockpit
    apt:
      pkg:
      - cockpit-networkmanager
      - cockpit-packagekit
      - cockpit-storaged
      update_cache: true      
      state: present
      
    tags: ["kiosk", "cockpit", "extras"]      
   
  - name: Start Cockpit
    service:
      name: cockpit.service
      state: started
      enabled: yes
    tags: ["kiosk", "cockpit", "extras"]         

